lwr:
  robot_name: lwr
  joints: 
      - lwr_a1_joint
      - lwr_a2_joint
      - lwr_e1_joint
      - lwr_a3_joint
      - lwr_a4_joint
      - lwr_a5_joint
      - lwr_a6_joint

  tip_name: lwr_7_link
  root_link: lwr_base_link
